### PR TITLE
Issue 94 signing issues

### LINKED ISSUE #94: Issues with signing in and signing out
# Description
On signing in with incorrect credentials. the app does not display a snackbar about the failed sign in.
On signing out, the login screen is not pushed to the screen, instead it just stays signed in until we restart the app.

# Relevant files
lib/Screens/LoginPage.dart
lib/Screens/Home.dart
Could be many others

### PR DESCRIPTION
**Pull request by mortal-ghost**
## Program
- [X] CodePeak
- [ ] Script Winter of Code
- [ ] None

## Issue
Fixes #94 

## Description
No snackbar on signing in was caused by a duplicated Scaffold in lib/Screens/LoginPage.dart which was removed.
Sign out issue was seemingly caused by Navigator pushing replacement onto nothing as when we signed in the login screen/register screen was automatically changed to home screen by the providers. (Not sure though, nothing else seemed wrong). Both lib/Screens/LoginPage.dart and lib/Screens/Register.dart are changed.

## Type of change
You can write manually also

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] The app runs properly
- [X] I have performed a self-review of my own code
- [X] I have formatted and commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
@mortal-ghost please merge the master branch of my repository

**Comment by mortal-ghost** [comment]
Is it done?

File: lib/main.dart [hunk 1]
```diff
@@ -52,7 +52,7 @@ class ScreensController extends StatelessWidget {
     final user = Provider.of<UserProvider>(context);
     switch (user.status) {
       case Status.Uninitialized:
-        return Splash();
+        return LoginPage();
       case Status.Unauthenticated:
       case Status.Authenticating:
```
Comment (Saransh-cpp) [inline lib/main.dart:57]: @mortal-ghost, I think the main issue was with a missing statement in `case Status.Unauthenticated:`? Why is `Splash` screen removed now?

File: lib/Screens/LoginPage.dart [hunk 2]
```diff
@@ -118,11 +116,6 @@ class _SignInState extends State<SignIn> {
                                       _passwordTextController.text)) {
                                     _key.currentState.showSnackBar(SnackBar(
                                         content: Text("Sign in failed")));
-                                  } else {
-                                    Navigator.pushReplacement(
-                                        context,
-                                        MaterialPageRoute(
-                                            builder: (c) => NavBar()));
```
Comment (Saransh-cpp) [inline lib/Screens/LoginPage.dart:125]: Shouldn't the `NavBar` screen be pushed when a user successfully authenticates?

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]

File: lib/main.dart (hunk 1 above)
Comment (mortal-ghost) [reply lib/main.dart:57]: I tried adding the login page on status.unauthenticated , the error persisted. It was also like this when the app functioned correctly. I think the problem was with the navigator, the NavBar was pushed as replacement when we did not really need to push anything as providers will listen to the authentication changes and return NavBar() in ScreensController. The navigator was actually pushing NavBar() onto the ScreensController widgets. That's why when we logged out, nothing happened because there was nothing to listen to the changes.

File: lib/main.dart [hunk 3]
```diff
@@ -52,7 +52,7 @@ class ScreensController extends StatelessWidget {
     final user = Provider.of<UserProvider>(context);
     switch (user.status) {
       case Status.Uninitialized:
-        return Splash();
+        return LoginPage();
```
Comment (Saransh-cpp) [inline lib/main.dart:55]:
```suggestion
        return Splash();
```

File: lib/main.dart [hunk 4]
```diff
@@ -52,7 +52,7 @@ class ScreensController extends StatelessWidget {
...
       case Status.Unauthenticated:
```
Comment (Saransh-cpp) [inline lib/main.dart:56]: Add `return LoginPage();` below this line

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
Thanks, @mortal-ghost! Great work! A few points -

1. Putting `LoginPage` in the `Uninitialized` case means that when the app is not initialized, the login page will be displayed. Let's say a user is already logged in and they open their app again, in this scenario the user will see the splash screen first, the logging page after that, and the home screen after that. We don't want this.
2. In the `Unauthenticated` case, the `LoginPage` should be displayed again as the user is not authenticated. Right now the login page is still displayed as the `case Status.Unauthenticated:` does not have a return or a break statement (fall through error).
3. While running your branch, I encountered an error with the `snackbar`. It is not being displayed on the `LoginPage` if the signing-in fails. I was able to fix this locally, let me know if you need the quick solution :)

File: lib/main.dart (hunk 3 above)
Comment (mortal-ghost) [reply lib/main.dart:55]: I got the *1 point, thank you very much.
*2 I will do that in a moment.
*3 This was one of the two issues I fixed. When I run the app, snackbar works correctly. I will check it again though.

File: nano.save [hunk 5]
```diff
@@ -0,0 +1,67 @@
+SizedBox(
```
Comment (Saransh-cpp) [inline nano.save:1]: We don't need this file, I think you added this by mistake

File: pubspec.lock [hunk 6]
```diff
@@ -7,7 +7,7 @@ packages:
       name: async
```
Comment (Saransh-cpp) [inline pubspec.lock:7]: Please revert back the changes in `pubspec.lock`

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
Thanks, @mortal-ghost! Looks awesome now! A few minor changes -

File: nano.save (hunk 5 above)
Comment (mortal-ghost) [reply nano.save]: Yeah, I don't know where this came from, I have deleted it

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @mortal-ghost! Looks awesome!
